### ISSUE TITLE
run eFEL in 32 bit environment on Mac

### ISSUE THREAD

**Issue by Yuxin1997** [BlueBrain/eFEL#147]
Hi, I am using a tool named Optimizer, which both need wxpython2.8(only this version) and efel. Because wxpython2.8 could only run in 32-bit environment so I forcibly change my environment by this code:
```
defaults write com.apple.versioner.python Prefer-32-Bit -bool yes
```
then when I import efel
```
>>> import efel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/efel/__init__.py", line 23, in <module>
    from efel.api import *
  File "/Library/Python/2.7/site-packages/efel/api.py", line 36, in <module>
    import efel.cppcore as cppcore
ImportError: dlopen(/Library/Python/2.7/site-packages/efel/cppcore.so, 2): no suitable image found.  Did find:
	/Library/Python/2.7/site-packages/efel/cppcore.so: mach-o, but wrong architecture
	/Library/Python/2.7/site-packages/efel/cppcore.so: mach-o, but wrong architecture
```
Is there any methods for me to run efel in 32 bit environment?

**Comment by wvangeit** [comment]
Hi,

Not sure how you force efel to be compiled with 32-bit support on your system. Did you try to maybe reinstall efel (did you use pip ?) after you've enable the Prefer-32-bit flag ?

I would also suggest that you ask the Optimizer developers to make their code compatible with newer versions of wxpython because I assume this situation won't be maintainable for much longer.

**Comment by Yuxin1997** [comment]
Hi, thanks so much for your reply. Thanks for your advice and I have emailed them.

Actually, I have tried to uninstall(after I enable prefer-32-bit flag) then install new one by pip but it still fails.
```
MacBook-Pro:~ yuxin$ sudo arch -32 /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python -m pip install git+git://github.com/BlueBrain/eFEL 
The directory '/Users/yuxin/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/yuxin/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting git+git://github.com/BlueBrain/eFEL
  Cloning git://github.com/BlueBrain/eFEL to /private/tmp/pip-req-build-deNDDH
  Installing build dependencies ... done
Requirement already satisfied: numpy>=1.6 in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from efel==3.0.31) (1.8.0rc1)
Requirement already satisfied: six in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from efel==3.0.31) (1.4.1)
Installing collected packages: efel
  Running setup.py install for efel ... done
Successfully installed efel-3.0.31
MacBook-Pro:~ yuxin$ sudo arch -32 /System/Library/Frameworks/Python.framework/Versions/2.7/bin/python
Python 2.7.10 (default, Aug 17 2018, 17:41:53) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import efel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/efel/__init__.py", line 23, in <module>
    from efel.api import *
  File "/Library/Python/2.7/site-packages/efel/api.py", line 36, in <module>
    import efel.cppcore as cppcore
ImportError: dlopen(/Library/Python/2.7/site-packages/efel/cppcore.so, 2): no suitable image found.  Did find:
	/Library/Python/2.7/site-packages/efel/cppcore.so: mach-o, but wrong architecture
	/Library/Python/2.7/site-packages/efel/cppcore.so: mach-o, but wrong architecture
```

I guess the reason might be that even I use 'Prefer 32-bit flag' and 'arch -32', efel stills use 64-bit python to build because my computer is 64 bit version. I noticed that in 2016 you push a commit that fix 32-bit building problem. I would like to know whether it has some connection.
![image](https://user-images.githubusercontent.com/38205562/49386943-a2df6980-f6ee-11e8-96e5-09db9b13e80d.png)

I really appreciate any help you offer. Thank you so much.

Yuxin

**Comment by wvangeit** [comment]
Yes, so if you have a 64-bit python I think it will be difficult/impossible to force a 32-bit compilation of eFEL. It seems it would be best to get a 64-bit version of wxpython (which then hopefully works with Optimizer).

(an alternative would be to use https://github.com/BlueBrain/BluePyOpt instead of Optimizer. This works with all the latest packages)

The commit that mentioned 32bit was just to make the unit tests pass on 32-bit machines, but it didn't change anything to the compilation process.

**Comment by Yuxin1997** [comment]
Wow BluePyOpt seems great!
Our lab would like to fit our in slice recording data in region we studied . We would like to get the parameters needed in NEURON.  I would like to confirm that whether it could be the extension of NEURON and could fit the parameters it need.
Thanks for all your advice!

**Comment by wvangeit** [comment]
Yes, indeed, BluePyOpt is mostly developed around NEURON, so it should fit your use case.

**Comment by Yuxin1997** [comment]
Thank you so much. I will drop Optimizer and use BluePyOpt :)

**Comment by Yuxin1997** [comment]
I also have a question regarding efel on python3. I use it well on python2 but it could not install with python3.
Here is the report.
```
bash-3.2$ python3 -m pip install efel
Collecting efel
  Using cached https://files.pythonhosted.org/packages/e1/c6/bda2cb6879e9a78fc80382d37e1714c0654e3fbdf85ea295d6eeb94a8353/efel-3.0.31.tar.gz
Requirement already satisfied: numpy>=1.6 in /Users/yuxin/anaconda3/lib/python3.7/site-packages (from efel) (1.15.1)
Requirement already satisfied: six in /Users/yuxin/anaconda3/lib/python3.7/site-packages (from efel) (1.11.0)
Building wheels for collected packages: efel
  Running setup.py bdist_wheel for efel ... error
  Complete output from command /Users/yuxin/anaconda3/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/8y/7p97mc4x1115qqytpytpb0jc0000gn/T/pip-install-jrxwktnv/efel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/8y/7p97mc4x1115qqytpytpb0jc0000gn/T/pip-wheel-90oujlh3 --python-tag cp37:
  Warning: 'keywords' should be a list, got type 'tuple'
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/efel
  copying efel/_version.py -> build/lib.macosx-10.7-x86_64-3.7/efel
  copying efel/io.py -> build/lib.macosx-10.7-x86_64-3.7/efel
  copying efel/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/efel
  copying efel/api.py -> build/lib.macosx-10.7-x86_64-3.7/efel
  copying efel/settings.py -> build/lib.macosx-10.7-x86_64-3.7/efel
  creating build/lib.macosx-10.7-x86_64-3.7/efel/pyfeatures
  copying efel/pyfeatures/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/efel/pyfeatures
  copying efel/pyfeatures/pyfeatures.py -> build/lib.macosx-10.7-x86_64-3.7/efel/pyfeatures
  copying efel/DependencyV5.txt -> build/lib.macosx-10.7-x86_64-3.7/efel
  creating build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/Utils.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/LibV1.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/LibV2.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/LibV3.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/LibV4.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/LibV5.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/FillFptrTable.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/DependencyTree.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/efel.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/cfeature.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/Global.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/mapoperations.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/types.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  copying efel/cppcore/eFELLogger.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
  UPDATING build/lib.macosx-10.7-x86_64-3.7/efel/_version.py
  set build/lib.macosx-10.7-x86_64-3.7/efel/_version.py to '3.0.31'
  running build_ext
  building 'efel.cppcore' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/efel
  creating build/temp.macosx-10.7-x86_64-3.7/efel/cppcore
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/yuxin/anaconda3/include -arch x86_64 -I/Users/yuxin/anaconda3/include -arch x86_64 -Iefel/cppcore/ -I/Users/yuxin/anaconda3/include/python3.7m -c efel/cppcore/cppcore.cpp -o build/temp.macosx-10.7-x86_64-3.7/efel/cppcore/cppcore.o
  warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
  efel/cppcore/cppcore.cpp:39:10: fatal error: 'cstddef' file not found
  #include <cstddef>
           ^~~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for efel
  Running setup.py clean for efel
Failed to build efel
twisted 18.7.0 requires PyHamcrest>=1.9.0, which is not installed.
Installing collected packages: efel
  Running setup.py install for efel ... error
    Complete output from command /Users/yuxin/anaconda3/bin/python3 -u -c "importsetuptools, tokenize;__file__='/private/var/folders/8y/7p97mc4x1115qqytpytpb0jc0000gn/T/pip-install-jrxwktnv/efel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/8y/7p97mc4x1115qqytpytpb0jc0000gn/T/pip-record-pxgyanjv/install-record.txt --single-version-externally-managed --compile:
    Warning: 'keywords' should be a list, got type 'tuple'
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/efel
    copying efel/_version.py -> build/lib.macosx-10.7-x86_64-3.7/efel
    copying efel/io.py -> build/lib.macosx-10.7-x86_64-3.7/efel
    copying efel/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/efel
    copying efel/api.py -> build/lib.macosx-10.7-x86_64-3.7/efel
    copying efel/settings.py -> build/lib.macosx-10.7-x86_64-3.7/efel
    creating build/lib.macosx-10.7-x86_64-3.7/efel/pyfeatures
    copying efel/pyfeatures/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/efel/pyfeatures
    copying efel/pyfeatures/pyfeatures.py -> build/lib.macosx-10.7-x86_64-3.7/efel/pyfeatures
    copying efel/DependencyV5.txt -> build/lib.macosx-10.7-x86_64-3.7/efel
    creating build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/Utils.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/LibV1.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/LibV2.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/LibV3.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/LibV4.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/LibV5.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/FillFptrTable.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/DependencyTree.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/efel.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/cfeature.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/Global.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/mapoperations.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/types.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    copying efel/cppcore/eFELLogger.h -> build/lib.macosx-10.7-x86_64-3.7/efel/cppcore
    UPDATING build/lib.macosx-10.7-x86_64-3.7/efel/_version.py
    set build/lib.macosx-10.7-x86_64-3.7/efel/_version.py to '3.0.31'
    running build_ext
    building 'efel.cppcore' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/efel
    creating build/temp.macosx-10.7-x86_64-3.7/efel/cppcore
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/yuxin/anaconda3/include -arch x86_64 -I/Users/yuxin/anaconda3/include -arch x86_64 -Iefel/cppcore/ -I/Users/yuxin/anaconda3/include/python3.7m -c efel/cppcore/cppcore.cpp -o build/temp.macosx-10.7-x86_64-3.7/efel/cppcore/cppcore.o
    warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
    efel/cppcore/cppcore.cpp:39:10: fatal error: 'cstddef' file not found
    #include <cstddef>
             ^~~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "/Users/yuxin/anaconda3/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/8y/7p97mc4x1115qqytpytpb0jc0000gn/T/pip-install-jrxwktnv/efel/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record/private/var/folders/8y/7p97mc4x1115qqytpytpb0jc0000gn/T/pip-record-pxgyanjv/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/8y/7p97mc4x1115qqytpytpb0jc0000gn/T/pip-install-jrxwktnv/efel/
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Thank you so much!

**Comment by Yuxin1997** [comment]
thank you so much!

**Comment by wvangeit** [comment]
Can this ticket be closed ?

**Comment by Yuxin1997** [comment]
sure, thank you so much
